/*
 * Values returned by KBGET/KBHIT for PC function keys
 */
#define	_UA		0x4800
#define	_DA		0x5000
#define	_LA		0x4B00
#define _RA		0x4D00
#define	_PU		0x4900
#define	_PD		0x5100
#define	_HO		0x4700
#define	_EN		0x4F00
#define	_INS	0x5200
#define	_DEL	0x5300
#define	_F1		0x3B00
#define	_F2		0x3C00
#define	_F3		0x3D00
#define	_F4		0x3E00
#define	_F5		0x3F00
#define	_F6		0x4000
#define	_F7		0x4100
#define	_F8		0x4200
#define	_F9		0x4300
#define	_F10	0x4400
#define	_CLA	0x7300
#define	_CRA	0x7400
#define	_CPU	0x8400
#define	_CPD	0x7600
#define	_CHO	0x7700
#define	_CEN	0x7500
