(* Release 3.10 *)
(*-------------------------------------------------------------------------*
*                                                                          *
*  ASCII.MOD - Core library interface                                      *
*                                                                          *
*  COPYRIGHT (C) 1987..1992 Clarion Software Corporation.                  *
*  All Rights Reserved                                                     *
*                                                                          *
*--------------------------------------------------------------------------*)

IMPLEMENTATION MODULE ASCII ;


END ASCII.
