(* Release 3.10 *)
(*-------------------------------------------------------------------------*
*                                                                          *
*  CORELIB.MOD - Core library                                              *
*                                                                          *
*  COPYRIGHT (C) 1987..1992 Clarion Software Corporation.                  *
*  All Rights Reserved                                                     *
*                                                                          *
*--------------------------------------------------------------------------*)

MODULE CoreLib;
IMPORT ASCII,InOut,RealInOut,Terminal,Strings ;

(* This Library is provided for easy conversion
   of existing programs.

   Its use is not recomended for new programs,
   as the TopSpeed M2 Library has all the functionality
   and is implemented more directly.

*)



END CoreLib.

