

*.PR  = .; c:\PR;
*.PI  = .; c:\PR;
*.DEF = .; c:\INCLUDE;
*.H   = .; c:\INCLUDE;
*.ITF = .; c:\INCLUDE;
*.HPP = .; c:\INCLUDE;
*.INC = .; c:\INCLUDE;
*.MOD = .; c:\SRC;
*.C   = .; c:\SRC;
*.PAS = .; c:\SRC;
*.CPP = .; c:\SRC;
*.A   = .; c:\SRC;

*.EXP = .; c:\EXP;
OVLLOAD.EXE = c:\SYS;

*.OBJ = .; c:\LIB;
*.LIB = .; c:\LIB;
*.DOC = .; c:\DOC;
*.DLL = .; c:\SYS;

*.HLP = c:\DOC;
